// <auto-generated />
namespace PrivateSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class backtobasics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(backtobasics));
        
        string IMigrationMetadata.Id
        {
            get { return "201903172101444_back-to-basics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
